apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qkgjxtn0l-python
  janus-idp.io/tekton: qkgjxtn0l-python
  backstage.io/kubernetes-id: qkgjxtn0l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qkgjxtn0l-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
